### ISSUE TITLE
Error with libtinfo.so.5 

### ISSUE THREAD

**Issue by hsx1** [BBillot/hypothalamus_seg#2]
Hi, I am trying to run hypo_seg as instructed but I get the following error message:

```
$ ./hypo_seg
hypothalamus_seg for Linux
/bin/sh: /tmp/_MEIxXCpZT/libtinfo.so.5: no version information available (required by /bin/sh)
Illegal instruction (core dumped)
```
despite `libtinfo.so.5` being installed. Is it possible that it's maybe searching at the wrong place?
I am running Ubuntu 18.04.5 LTS.

**Comment by BBillot** [comment]
Hi,
I've never had this error before.
I wasn't even aware of this library, and looking at the following
related problems I do not think the problem is with hypo_seg:
https://github.com/commercialhaskell/stack/issues/1012
https://github.com/smallhadroncollider/taskell/issues/12
These suggest that could be an error of symlinking.

In my case I have this library installed
under /lib/x86_64-linux-gnu/libtinfo.so.5, and it is under /lib64 on the
cluster I'm using.
Maybe you could add the path to the library:
export PATH=/path/to/libtinfo.so.5${PATH:+:${PATH}} ?

Note that hypo_seg is now available with the development version of
FreeSurfer:
https://surfer.nmr.mgh.harvard.edu/fswiki/HypothalamicSubunits
with the dev version of FS available here:
https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/dev/

Best,
Benjamin

**Comment by hsx1** [comment]
Hi Benjamin,

thank you for your quick response.
Turns out the temp folder of the server I was using ran out of space.
It's working great now.

Cheers Hannah
