### ISSUE TITLE
Questions about QC

### ISSUE THREAD

**Issue by alaurell** [BBillot/hypothalamus_seg#6]
Hi,

I have run the hypothalamic segmentation and are currently working through some quality control visual inspection of the images. Apart from a small number of images where whole subunits are missing, there are also a subset of images where there are voxels missing. This seems to usually affect the anterior-inferior and posterior subunits (see attached images). Do you have any thoughts about whether to include images with one or a few missing voxels?

Best wishes
Axel

![image](https://github.com/BBillot/hypothalamus_seg/assets/135816898/f575380e-aa26-48a0-9ec4-3a3bf59957fa)
![image](https://github.com/BBillot/hypothalamus_seg/assets/135816898/02dfc60a-afd1-4e11-9558-6130c0bf9c97)
![image](https://github.com/BBillot/hypothalamus_seg/assets/135816898/fe83a749-9b76-40f5-9bfd-6c7a08b6df20)
![image](https://github.com/BBillot/hypothalamus_seg/assets/135816898/53354032-1886-497f-b82c-ecea18a03049)

**Comment by BBillot** [comment]
Hi!
besides obvious fails, QCing hypothalamic segmentations can be a delicate matter. It'd be quite complicated for me to judge those ones just from these 4 screenshots, because we're talking here about 3D volumes. This may sound stupid, but 3D makes all the difference. For example, head rotations might sometimes explain why contralateral subunits are not symmetric (such as the anterior-superior in the first image), or why some voxels appear to be missing (2nd image). You would have to look at the 3D object to put these 2D image in context.
On the other hand I see nothing wrong with the 3rd and 4th images. The two mamillary bodies are not always touching each other, especially at the  posterior end.

The I think, for the bordline cases, including or rejecting a segmentation can be up to you. You can adopt a restrictive approach, where you only keep the segmetnations for which you're 100% sure, or you could be a bit more tolerant. The approach you decided on can also be motivated by the number of cases that you have: if you have not a lot of subjects, you may be more enclined to keep as many as possible, and to be more tolerant to borderline cases. I think this is typically the kind of thing you need to acknowledge in your paper. Then, it can only depend on if you;re only interested in a specific subunit, in which case potential errors for other regions may be less important. 

Sorry, it's hard for me to come up with very specific rules, but I hope this still helps you.
Best
Benjamin

**Comment by alaurell** [comment]
Hi Benjamin,

Thank you that is really helpful. I have a small number of images where at least one subunit is completely missing. In some of them there is a gap, whereas in others it looks visually like the neighbouring subunits have been 'oversegmented'. In your opinion, if a subunit is missing, should I exclude that subject completely from further analysis?

Best wishes,

Axel

**Comment by BBillot** [comment]
Yes! if a subunit is missing, then the segmentation is definitely a fail.
